### ISSUE TITLE
Опечатка в названии метода

### ISSUE THREAD

**Issue by titovneolant** [stv-ckv/NEOSYNTEZ-API#10]
Метод создания нового класса из раздела **structure/entities**:
Синхронная версия:
`public JObject CreareNewEntity(NeosyntezClass neosyntezClass)`
Асинхронная версия:
`public async Task<JObject> CreareNewEntityAsync(NeosyntezClass neosyntezClass)`

В обоих случаях вместо _Crea**r**e_ должно быть _Crea**t**e_

[AB#261](https://dev.azure.com/neolantservice4/644f90da-893b-4e55-86c6-90b8ec342f2d/_workitems/edit/261)

**Comment by masterged** [comment]
исправленно в версии 1.6.1
