### ISSUE TITLE
Кавычки в наименовании файла

### ISSUE THREAD

**Issue by mrKypo** [stv-ckv/NEOSYNTEZ-API#14]
При скачивании фала с НС через библиотеку, некоторые файлы скачиваются с кавычками в начале и конце наименования. Возможно связано с расширением файла. 

[AB#303](https://dev.azure.com/neolantservice4/644f90da-893b-4e55-86c6-90b8ec342f2d/_workitems/edit/303)

**Comment by masterged** [comment]
Данное поведение связано с https://github.com/dotnet/runtime/issues/32765

**Comment by masterged** [comment]
Исправлено в версии 1.6.1
