### ISSUE TITLE
Ошибка метода GetUserInfo.

### ISSUE THREAD

**Issue by mrKypo** [stv-ckv/NEOSYNTEZ-API#7]
В процессе работы с API Неосинтез возникла проблема при обращении к методу userinfo.
Аутентифицированная учетная запись(доменная) с правами администратора k.isakov получает токен доступа, обращается к API и получает данные. Но при обращении к методу /connect/userInfo получает ошибку.
Сервер с адресом https://kaskad-dev.io.neolant.su/ вернул ошибку  в ответ на запрос /connect/userInfo
System.Net.HttpStatusCode.Unauthorized

AB#257

**Comment by masterged** [comment]
GET /connect/userinfo возвращает 200 статус и информацию о текущем пользователя в виде json для авторизованных пользователей. Это api IdentityServer
 
Возвращаемые поля:

sub - идентификатор текущего пользователя
name - название текущего пользователя
role - название роли или массив названий ролей
Данное API работает для запросов авторизованных с помощью Bearer токена или куки.
Для не авторизованных пользователей возвращается статус 401.
 
Для вьювера типа "Внешний контент", генерируется одноразовый, короткоживущий JWT токен. Данный тип токена уже содержит в себе всю необходимую информацию: * sub - идентификатор текущего пользователя.

name - название текущего пользователя.
role - название роли или массив названий ролей.
Для декодирования JWT токена можно использовать как сторонние готовые библиотеки, так и делать это самостоятельно.
