### ISSUE TITLE
Неточные названия методов API models/types

### ISSUE THREAD

**Issue by titovneolant** [stv-ckv/NEOSYNTEZ-API#9]
Есть следующие методы раздела **models/types**:

- `Task<BaseObject<long>> CreateNewModelTypeAsync(BaseObject<long> type)`
- `Task<IEnumerable<BaseObject<long>>> GetModelTypesAsync()`
- `Task ChangeModelTypeAsync(ChangedObject<long, BaseObject<long>> changedObject)`
- `Task DeleteModelTypeAsync(IEnumerable<long> ids)`
- ... и их синхронные братья

На данный момент названия методов и их описание не отражают их сути, более того, запутывают, т.к. в модели есть поле _Type_, к которому эти методы не имеют никакого отношения. На деле же они все относятся к полю _ContentType_ у модели. Предлагаю переименовать данные методы с учетом их назначения, в том числе и поправить описание методов и параметров.

[AB#260](https://dev.azure.com/neolantservice4/644f90da-893b-4e55-86c6-90b8ec342f2d/_workitems/edit/260)

**Comment by masterged** [comment]
Переименовано в версии 1.6.2
